### ISSUE TITLE
Keyboard short-cut `ctrl-k` has to be manually added after extension installation. 

### ISSUE THREAD

**Issue by simphotonics** [hironobu-s/vsc-emacs-kill-line#1]
```
Visual Studio Code Version: 1.49.3
Commit: 2af051012b66169dde0c4dfae3f5ef48f787ff69
Date: 2020-10-02T17:56:11.027Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-48-generic
```

@hironobu-s, I just installed `vsc-emacs-kill-line` version `0.0.4` and wanted to let you know that it is working as 
intended but only after editing `keybindings.json` and registering a new keyboard short-cut for `ctrl+k`:
```Json
// keybindings.json
// Place your key bindings in this file to override the defaultsauto[]
[   
    {
        "key": "ctrl+k",
        "command": "extension.emacsKillLine.kill-line",
        "when": "editorTextFocus"
    },
    {   "key": "ctrl+y",
        "command": "editor.action.clipboardPasteAction",
        "when": "editorTextFocus"
    }
]
```
It might be useful for other users if you mention it in the documentation. 

Thank you for creating this useful extension.

**Comment by hironobu-s** [comment]
Thank you for your suggestion. This instruction is useful. I update the document soon.

**Comment by hironobu-s** [comment]
@simphotonics Thank you for your suggestion. This instruction is useful. I update the document soon.

**Comment by hironobu-s** [comment]
done
